tareas/urls.py
from tar.admin import admin_site
from django.urls import path, re_path
from tar.views import (
    lista_tareas,
    RevisarTareasListView,
    attachment,
    descargar_tarea,
    descargar_imagen,
    aprobar_rechazar,
    guardar_nota,
    detalles_tarea,
    detalles_tarea_entregada,
    lista_estudiantes,
    estudiante_tareas,
)
from enc.views import (
    encuesta,
    encuesta_instancia_ultimo_cambio,
    encuesta_instancia_siguiente_pregunta,
    configurar_preguntas,
    mostrar_resultados,
    crear_encuesta_desde_plantilla,
)
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin_site.urls),
    path('', lista_tareas, name='lista-tareas'),
    path('revisar', RevisarTareasListView.as_view(), name='revisar-tareas'),
    path('revisar/aprobar_rechazar', aprobar_rechazar, name='revisar-tareas'),
    path('revisar/guardar_nota', guardar_nota, name='guardar-nota'),
    path('tarea/<tarea_id>', detalles_tarea, name='detalles-tarea'),
    path('tarea/entregada/<tarea_estudiante_id>', detalles_tarea_entregada, name='detalles-tarea-entregada'),
    path('adjuntar', attachment, name='adjuntar-tarea'),
    re_path('^adjuntos/', descargar_tarea, name='descargar-tarea'),
    re_path('^imagen/', descargar_imagen, name='descargar-imagen'),
    path('estudiantes', lista_estudiantes, name='lista-estudiantes'),
    path('estudiante/<estudiante_id>', estudiante_tareas, name='estudiante-tareas'),
    path('preguntas', encuesta, name='encuesta'),
    path('api/encuesta_instancia/<encuesta_instancia_id>/ultimo_cambio',
        encuesta_instancia_ultimo_cambio, name='encuesta-ultimo-cambio'),
    path('encuesta_instancia/<encuesta_instancia_id>/siguiente_pregunta',
        encuesta_instancia_siguiente_pregunta, name='encuesta-siguiente-pregunta'),
    path('preguntas/<encuesta_plantilla_id>/configurar', configurar_preguntas, name='configurar-preguntas'),
    path('preguntas/mostrar_resultados', mostrar_resultados, name='mostrar-resultados'),
    path('encuesta_instancia/nueva', crear_encuesta_desde_plantilla, name='crear-encuesta-desde-plantilla'),
]

enc/models.py
from django.utils import timezone
from django.db import models
from django.utils.translation import gettext_lazy as _

from tar.models import Estudiante, Curso

class EncuestaPlantilla(models.Model):
    """EncuestaPlantilla es una colleción ordenada de Preguntas que sirven para
    crear una EncuestaInstancia. Su función principal es permitir el reuso
    fácil de una colleción de Preguntas en más que una EncuestaInstancia.
    """

    id = models.BigAutoField(primary_key=True)

    nombre = models.CharField(
        _('nombre'),
        max_length=255,
    )

    def __str__(self):
        return self.nombre

    class Meta:
        verbose_name_plural = 'EncuestaPlantilla'


class Pregunta(models.Model):
    """Pregunta representa una pregunta de selección múltiple. Cada Pregunta
    pertenece a una EncuestaPlantilla y tiene un orden respeto a las otras
    Preguntas que hacen parte de la EncuestaPlantilla.

    Una Pregunta tiene al menos una PreguntaOpción asociada, que representa una
    opción posible para una respuesta.

    Una Pregunta puede permitir una sola respuesta (por defecto) o varias
    (respuesta_multiple=True).
    """

    id = models.BigAutoField(primary_key=True)

    encuesta_plantilla = models.ForeignKey(
        EncuestaPlantilla,
        models.CASCADE,
        verbose_name=_('encuesta plantilla'),
    )

    orden = models.IntegerField(
        _('Orden'),
    )

    texto = models.CharField(
        _('Pregunta'),
        max_length=255,
    )
    
    respuesta_multiple = models.BooleanField(
        default=False,
        verbose_name=_('Respuesta múltiple'),
    )

    id_editor = models.IntegerField(
        _('ID usado en el editor'),
    )

    def __str__(self):
        return "{}: {}".format(self.encuesta_plantilla, self.texto)

    class Meta:
        verbose_name_plural = 'Preguntas'

class PreguntaOpcion(models.Model):
    """PreguntaOpcion representa una respuesta posible a una Pregunta.

    Cada PreguntaOpcion tiene un orden relativo a las otras PreguntaOpciones
    asociadas con la Pregunta.
    """

    id = models.BigAutoField(primary_key=True)

    pregunta = models.ForeignKey(
        Pregunta,
        models.CASCADE,
        verbose_name=_('pregunta'),
    )

    orden = models.IntegerField(
        _('Orden'),
    )

    texto = models.CharField(
        _('Texto'),
        max_length=255,
    )
    def __str__(self):
        return self.texto

    class Meta:
        verbose_name_plural = 'Opciones para Pregunta'


class EncuestaInstancia(models.Model):
    """EncuestaInstancia representa una la realización de una encuesta con los
    Estudiantes de un Curso dado.

    Una EncuestaInstancia se genera desde una EncuestaPlantilla.

    Se muestra a los estudiantes la EncuestaInstancia activa. Solo debe ser una
    EncuestaInstancia activa en un momento dado.
    """

    id = models.BigAutoField(primary_key=True)

    curso = models.ForeignKey(
        Curso,
        models.CASCADE,
        verbose_name=_('cursos'),
    )

    encuesta_plantilla = models.ForeignKey(
        EncuestaPlantilla,
        models.CASCADE,
        verbose_name=_('encuesta plantilla'),
    )

    activo = models.BooleanField(
        default=True,
        verbose_name=_('Activo'),
    )

    tiempo = models.DateTimeField(
        _('Tiempo'),
        default=timezone.now
    )

    def __str__(self):
        return "{} - {}".format(self.curso, self.encuesta_plantilla)


class PreguntaInstancia(models.Model):
    """PreguntaInstancia mantiene el estado mutable de una Pregunta asociado con una
    EncuestaInstancia. Este estado mutable consiste de que si la
    PreguntaInstancia es la instancia activa, si se deben mostrar los
    resultados y el orden.

    El orden de una PreguntaInstancia hereda su orden desde la Pregunta
    asociada, pero este se puede cambiar cuando se agrega nuevas preguntas a
    una EncuestaInstancia.
    """

    id = models.BigAutoField(primary_key=True)

    encuesta_instancia = models.ForeignKey(
        EncuestaInstancia,
        models.CASCADE,
        verbose_name=_('encuesta instancia'),
    )

    pregunta = models.ForeignKey(
        Pregunta,
        models.CASCADE,
        verbose_name=_('Pregunta'),
    )


    activo = models.BooleanField(
        default=False,
        verbose_name=_('Activo'),
    )

    tiempo = models.DateTimeField(
        _('Tiempo'),
        default=timezone.now
    )

    mostrar_resultados = models.BooleanField(
        default=False,
        verbose_name=_('Mostrar resultados'),
    )

    orden = models.IntegerField(
        _('Orden'),
        blank=True,
    )

    def save(self, *args, **kwargs):
        # Si estamos guardando una nueva PreguntaInstancia,
        # fijar el orden al orden de la Pregunta asociada.
        if self._state.adding:
            self.orden = self.pregunta.orden
        super().save(*args, **kwargs)

    def __str__(self):
        return "{}: {}".format(self.encuesta_instancia, self.pregunta)


class Respuesta(models.Model):
    """Respuesta representa una elección de una PreguntaOpción por parte de un
    Estudiante.

    Una PreguntaInstancia puede tener varias Respuestas de un Estudiante dado
    si corresponde a una Pregunta de respuesta múltiple.
    """

    pregunta_opcion = models.ForeignKey(
        PreguntaOpcion,
        models.CASCADE,
        verbose_name=_('Opción para Pregunta'),
    )

    pregunta_instancia = models.ForeignKey(
        PreguntaInstancia,
        models.CASCADE,
        verbose_name=_('Pregunta instancia'),
    )

    estudiante = models.ForeignKey(
        Estudiante,
        models.CASCADE,
        verbose_name=_('Estudiante'),
    )

    tiempo = models.DateTimeField(
        _('Tiempo'),
        default=timezone.now
    )

    def __str__(self):
        return "Pregunta {}: {} eligió {}".format(self.pregunta_opcion.pregunta.id, self.estudiante, self.pregunta_opcion.id)

    class Meta:
        verbose_name_plural = 'Respuesta para Pregunta'

enc/templates/configurar_preguntas.html
<!DOCTYPE html>
<html>
<head>
<link rel="icon" href="data:image/svg+xml,%3Csvg%20xmlns='http://www.w3.org/2000/svg'%20viewBox='0%200%2016%2016'%3E%3Ctext%20x='0'%20y='12'%20style='filter:%20invert(58%)%20sepia(63%)%20saturate(364%)%20hue-rotate(85deg);'%3E●%3C/text%3E%3C/svg%3E" type="image/svg+xml" />
<meta name="viewport" content="width=device-width, initial-scale=1">
<style>
{% include 'estilos_base.css' %}
.content {
  margin: 0 auto 100px;
  max-width: 700px;
  height: 250px;
  padding: 0 20px 0 20px;
}
.flex-column {
  flex-direction: column;
}
.crear-encuesta {
  width: max-content;
}
</style>
</head>
<body>
<header>
  <div>
    <h1></h1>
    <h2><a class="nolink" href="/">Tareas</a></h2>
    <span class="right">{{ first_name|default('') }} {{ last_name|default('') }}</span>
  </div>
</header>
<div class="content">
  <h2>Preguntas</h2>
  <form action="/preguntas/{{ encuesta_plantilla_id }}/configurar" method="post">
    <textarea name="preguntas_yaml" rows="20" cols="80">
{%- for p in preguntas %}
{{ p.id_editor }}: {{ p.texto }}{% if p.respuesta_multiple %}*{% endif %}
  {%- for o in p.preguntaopcion_set.all() %}
- {% if o.texto == 'no'%}"no"{% else %}{{ o.texto }}{% endif %}
  {%- endfor %}
{% endfor %}
    </textarea>
    {{ csrf_input }}
    <br />
    <input class="guardar" type="submit" value="Guardar" />
  </form>
  <form class="flex flex-column" action="/encuesta_instancia/nueva" method="post">
    <p>Crear encuesta desde esta plantilla</p>
    <div>
      <label for="curso">Curso: </label>
      <select name="curso">
{% for c in cursos %}
        <option value="{{ c.id }}">{{ c.nombre }}</option>
{% endfor %}
      </select>
    </div>
    {{ csrf_input }}
    <input type="hidden" name="encuesta_plantilla_id" value="{{ encuesta_plantilla_id }}" />
    <input type="submit" class="crear-encuesta" value="Crear encuesta" />
  </form>
</div>
</body>
</html>

enc/templates/encuesta.html
<!DOCTYPE html>
<html>
<head>
<link rel="icon" href="data:image/svg+xml,%3Csvg%20xmlns='http://www.w3.org/2000/svg'%20viewBox='0%200%2016%2016'%3E%3Ctext%20x='0'%20y='12'%20style='filter:%20invert(58%)%20sepia(63%)%20saturate(364%)%20hue-rotate(85deg);'%3E●%3C/text%3E%3C/svg%3E" type="image/svg+xml" />
<meta name="viewport" content="width=device-width, initial-scale=1">
<style>
{% include 'estilos_base.css' %}
.content {
  margin: 0 auto 100px;
  max-width: 700px;
  height: 250px;
  padding: 0 20px 0 20px;
}
.content p, .content li {
  margin: 0.3em 0;
  font-size: 1.2em;
}
.content ol {
  padding-left: 1.2em;
}
{%- if not mostrar_resultados %}
input[type='radio'], input[type='checkbox'] {
  transform: scale(1.5);
  margin: 0.4em;
}
label {
  font-size: 1.4em;
  margin-left: 0.4em;
}
input.guardar {
  width: 25%;
  height: 2.2em;
  font-size: 1.2em;
}
.flex-dir-col {
  flex-direction: column;
}
.row {
  align-items: start;
  margin-bottom: 1em;
}
{% else %}
.grid {
  width: 100%;
  height: 100%;
  display: flex;
  justify-content: center;
  border-bottom: 2px solid #aaa;
  background: repeating-linear-gradient(0deg, transparent, transparent 24.3%, #ccc 25%);
  margin-bottom: 50px;
}
.bar {
  background-color: #f17020;
  width: 45px;
  height: var(--bar);
  align-self: flex-end;
  margin: 0 auto;
  border-radius: 3px 3px 0 0;
  position: relative;
}
.bar::after {
  content: attr(data-count);
  top: -3em;
  padding: 20px;
  position: absolute;
}
.bar::before {
  content: attr(data-name);
  top: 100%;
  padding: 10px 0 0 20px;
  position: absolute;
}
{%- endif %}
</style>
{%- if mostrar_resultados or request.user.is_staff %}
<script>
let t = {{ tiempo_ultimo_cambio }};
const timer = ms => new Promise(res => setTimeout(res, ms))
f = async () => {
  while (true) {
    let r = await fetch('/api/encuesta_instancia/{{ encuesta_instancia_id }}/ultimo_cambio');
    let t2 = await r.text();
    if(t != t2) {
      window.location.reload(false);   
    }
    await timer(3000);
  }
}
f();
</script>
{%- endif %}
</head>
<body>
<header>
  <div>
    <h1></h1>
    <h2><a class="nolink" href="/">Tareas</a></h2>
    <span class="right">{{ first_name|default('') }} {{ last_name|default('') }}</span>
  </div>
</header>
{%- if pregunta %}
  {%- if not mostrar_resultados %}
<div class="content">
  <h2>{{ pregunta.texto }}</h2>
  <form class="flex flex-dir-col" action="/preguntas" method="post">
      {% for o in opciones %}
        {%- if pregunta.respuesta_multiple %}
    <div class="flex row">
    <input type="checkbox" id="{{ o.id }}" name="opcion_id" value="{{ o.id }}">
    <label for="{{ o.id }}">{{ o.orden|orden_como_letra }}. {{ o.texto }}</label></br>
    </div>
	{% else %}
    <div class="flex row">
    <input type="radio" id="{{ o.id }}" name="opcion_id" value="{{ o.id }}">
    <label for="{{ o.id }}">{{ o.orden|orden_como_letra }}. {{ o.texto }}</label></br>
    </div>
        {%- endif %}
      {% endfor %}
    <input type="hidden" name="pregunta_instancia_id" value="{{ pregunta_instancia.id }}" />
    {{ csrf_input }}
    <br />
    <input class="guardar" type="submit" value="Guardar" />
  </form>
{%- if request.user.is_staff %}
    <form class="flex" action="/preguntas/mostrar_resultados" method="post">
      <input type="hidden" name="pregunta_instancia_id" value="{{ pregunta_instancia.id }}" />
      {{ csrf_input }}
      <input class="right" type="submit" value="Mostrar resultados" />
    </form>
    <p>Respuestas: {{ respuestas|length }}</p>
{%- endif %}
</div>
  {% else %}
<div class="content">
  <h2>Respuestas: {{ pregunta.texto }}</h2>
  <div class="grid">
    {%- for r in resultados %}
    <div class="bar" style="--bar:{{ r.bar_value }}%;" data-name="{{ r.orden|orden_como_letra }}." data-count="{{ r.conteo }}"></div>
    {%- endfor %}
  </div>
  <ol type="a">
    {%- for r in resultados %}
  <li>{{ r.texto }}</li>
    {%- endfor %}
  </ol>
    {%- if request.user.is_staff %}
  <form class="flex" action="/encuesta_instancia/{{ encuesta_instancia_id }}/siguiente_pregunta" method="post">
    {{ csrf_input }}
    <input class="right" type="submit" value="{{ texto_boton_admin }}" />
  </form>
    {%- else %}
      {%- if respuestas|length > 1 %}
  <p><strong>Elegiste las opciones {{ respuestas|map(attribute='pregunta_opcion')|map(attribute='orden')|map('orden_como_letra')|join(', ') }}.</strong></p>
      {%- else %}
  <p><strong>Elegiste la opción {{ respuestas[0].pregunta_opcion.orden|orden_como_letra }}.</strong></p>
      {%- endif %}
    {%- endif %}
</div>
  {%- endif -%}
{% else %}
<div class="content">
<br />
<p>No hay preguntas activas en este momento. Espera hasta que los profes activen nuevas preguntas.</p>
</div>
{%- endif %}
</body>
</html>